/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doutorado.tese.view.teste.scalability;

import doutorado.tese.control.business.visualizations.glyph.Glyph;
import doutorado.tese.util.Constantes;
import doutorado.tese.control.mb.testeMB.scalabilityMB.SetUpScalabilityTestMB;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Anderson (LABVIS)
 */
public class PainelDeTeste extends javax.swing.JPanel {

    private AreaCallback areaCallback;
    private final SetUpScalabilityTestMB scalabilityTestMB;

    /**
     * Creates new form PainelDeTeste
     */
    public PainelDeTeste() {
        scalabilityTestMB = new SetUpScalabilityTestMB();
        initComponents();
        this.areaCallback = (HashMap<String, Integer> areas) -> {
        };

    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        Graphics2D g2d = (Graphics2D) g;
        Color coritem = null;

        //desenho esquerda
        coritem = scalabilityTestMB.getInputConfigs().get("coritem") >= 0
                ? Color.decode(Constantes.getCor()[scalabilityTestMB.getInputConfigs().get("coritem")])
                : Color.decode(Constantes.getCor()[Constantes.getCor().length - 1]);
        g2d.setColor(coritem);
        g2d.fillRect(scalabilityTestMB.getInputConfigs().get("x"), scalabilityTestMB.getInputConfigs().get("y"),
                scalabilityTestMB.getInputConfigs().get("width"), scalabilityTestMB.getInputConfigs().get("height"));
        g2d.setColor(Color.BLACK);
        g2d.drawRect(scalabilityTestMB.getInputConfigs().get("x"), scalabilityTestMB.getInputConfigs().get("y"),
                scalabilityTestMB.getInputConfigs().get("width"), scalabilityTestMB.getInputConfigs().get("height"));

        ArrayList<Glyph> listItemInput = new ArrayList<>();
        scalabilityTestMB.getItemInput().getGlyph().paint(g2d);
        scalabilityTestMB.getItemInput().getGlyph().getChildren(listItemInput);
        g2d.setClip(0, 0, getBounds().width, getBounds().height);

        this.areaCallback.areaUpdated(scalabilityTestMB.getAreas());
        
        //desenho direita
        g2d.setColor(coritem);
        g2d.fillRect(scalabilityTestMB.getItemOutput().getBounds().x, scalabilityTestMB.getItemOutput().getBounds().y,
                scalabilityTestMB.getInputConfigs().get("width"), scalabilityTestMB.getInputConfigs().get("height"));
        g2d.setColor(Color.BLACK);
        g2d.drawRect(scalabilityTestMB.getItemOutput().getBounds().x, scalabilityTestMB.getItemOutput().getBounds().y,
                scalabilityTestMB.getInputConfigs().get("width"), scalabilityTestMB.getInputConfigs().get("height"));

        ArrayList<Glyph> listItemOutput = new ArrayList<>();
        scalabilityTestMB.getItemOutput().getGlyph().paint(g2d);
        scalabilityTestMB.getItemOutput().getGlyph().getChildren(listItemOutput);
        g2d.setClip(0, 0, getBounds().width, getBounds().height);
    }

    public void setAreaCallback(AreaCallback areaCallback) {
        this.areaCallback = areaCallback;
    }

    public interface AreaCallback {

        public void areaUpdated(HashMap<String, Integer> areas);
    }

    public void setInputConfigs(HashMap<String, Integer> inputConfigs) {
        scalabilityTestMB.setInputConfigs(inputConfigs);
        scalabilityTestMB.configLayersInput();
        repaint();
    }

    public void updateOutput(HashMap<String, Boolean> output) {
        scalabilityTestMB.setOutputConfigs(output);
        scalabilityTestMB.configLayersOutput();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
