/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doutorado.tese.view.teste.visibility;

import doutorado.tese.control.business.visualizations.glyph.Glyph;
import doutorado.tese.util.Constantes;
import doutorado.tese.control.mb.testeMB.scalabilityMB.SetUpVisibilityTestMB;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Anderson (LABVIS)
 */
public class PainelDeTeste extends javax.swing.JPanel {

    private AreaCallback areaCallback;
    private SetUpVisibilityTestMB visibilityTestMB;

    /**
     * Creates new form PainelDeTeste
     */
    public PainelDeTeste() {
        initComponents();
        this.areaCallback = (HashMap<String, Integer> areas) -> {
        };
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        Graphics2D g2d = (Graphics2D) g;
        Color coritem = null;

        //desenho esquerda
        coritem = getVisibilityTestMB().getInputConfigs().get("coritem") >= 0
                ? Color.decode(Constantes.getCorTreemap()[getVisibilityTestMB().getInputConfigs().get("coritem")])
                : Constantes.ALICE_BLUE;
        g2d.setColor(coritem);
        g2d.fillRect(getVisibilityTestMB().getInputConfigs().get("x"), getVisibilityTestMB().getInputConfigs().get("y"),
                getVisibilityTestMB().getInputConfigs().get("width"), getVisibilityTestMB().getInputConfigs().get("height"));
        g2d.setColor(Color.BLACK);
        g2d.drawRect(getVisibilityTestMB().getInputConfigs().get("x"), getVisibilityTestMB().getInputConfigs().get("y"),
                getVisibilityTestMB().getInputConfigs().get("width"), getVisibilityTestMB().getInputConfigs().get("height"));

        ArrayList<Glyph> listItemInput = new ArrayList<>();
        getVisibilityTestMB().getItemInput().getGlyph().paint(g2d);
//        getVisibilityTestMB().getItemInput().getGlyph().getChildren(listItemInput);
        g2d.setClip(0, 0, getBounds().width, getBounds().height);

        this.areaCallback.areaUpdated(getVisibilityTestMB().getAreas());
        //desenho direita
//        g2d.setColor(coritem);
//        g2d.fillRect(scalabilityTestMB.getItemOutput().getBounds().x, scalabilityTestMB.getItemOutput().getBounds().y,
//                scalabilityTestMB.getInputConfigs().get("width"), scalabilityTestMB.getInputConfigs().get("height"));
//        g2d.setColor(Color.BLACK);
//        g2d.drawRect(scalabilityTestMB.getItemOutput().getBounds().x, scalabilityTestMB.getItemOutput().getBounds().y,
//                scalabilityTestMB.getInputConfigs().get("width"), scalabilityTestMB.getInputConfigs().get("height"));
//
//        ArrayList<Glyph> listItemOutput = new ArrayList<>();
//        scalabilityTestMB.getItemOutput().getGlyph().paint(g2d);
//        scalabilityTestMB.getItemOutput().getGlyph().getChildren(listItemOutput);
//        g2d.setClip(0, 0, getBounds().width, getBounds().height);
    }

    public void setAreaCallback(AreaCallback areaCallback) {
        this.areaCallback = areaCallback;
    }

    public interface AreaCallback {

        public void areaUpdated(HashMap<String, Integer> areas);
    }

    public void setInputConfigs(HashMap<String, Integer> inputConfigs) {
//        getVisibilityTestMB().setInputConfigs(inputConfigs);
//        setFamilia2Desenho(visibilityTestMB.configLayersInput());
//        setFamilia2Desenho(getVisibilityTestMB().family2Draw());
        repaint();
    }

    public void updateOutput(HashMap<String, Boolean> output) {
        getVisibilityTestMB().setOutputConfigs(output);
//        scalabilityTestMB.configLayersOutput();
//        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(240, 248, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the visibilityTestMB
     */
    public SetUpVisibilityTestMB getVisibilityTestMB() {
        return visibilityTestMB;
    }

    /**
     * @param visibilityTestMB the visibilityTestMB to set
     */
    public void setVisibilityTestMB(SetUpVisibilityTestMB visibilityTestMB) {
        this.visibilityTestMB = visibilityTestMB;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
